### ISSUE TITLE
Error when getting room using IRC adapter

### ISSUE THREAD

**Issue by tpbowden** [hubot-scripts/hubot-standup-alarm#11]
ERROR ERROR: Not sure who to send to. envelope= { room: undefined } is logged when the standup should be called.

00:10 tom: hubot list standups in every room
00:10 hubot: Here's the standups for every room:
00:10 hubot: Room: undefined, Time: 00:09

**Comment by tpbowden** [comment]
Never mind the fix is there just not on NPM

**Comment by shaundon** [comment]
I'll get the NPM version updated ^^
