### ISSUE TITLE
Exclude day of the week?

### ISSUE THREAD

**Issue by MrMMorris** [hubot-scripts/hubot-standup-alarm#19]
Really nit picky here, but we work from home on Fridays and do not have standup. Would it be much of a hassle to be able to do something like `create standup 11:00 not friday`?

**Comment by andrhamm** [comment]
:+1:

**Comment by mkjaer** [comment]
In the Middle East we work Sunday to Thursday, so defining what a work week is would be helpful :)

**Comment by LTheobald** [comment]
I added #28 which included the ability to specify a single date but I can take a look at extending that.  I think having a range (Mon-Fri) would be better than "Not Friday". It's a little more explicit so it ensures there's no Sat/Sun either.

As for the defining what the work week is, that's simple enough. Maybe allow the user to configure the cron somewhat through an environment variable.
