### ISSUE TITLE
Saved data

### ISSUE THREAD

**Issue by mkjaer** [hubot-scripts/hubot-standup-alarm#26]
Does the standups get saved to disk somewhere?
I run my hubot through a docker container and need to know which path to add as a volume. With my limited JS knowledge I couldn't find anything in the sourcecode about data getting saved.

**Comment by shaundon** [comment]
They go into Hubot's brain, which is a Redis store. I think it's then up to your Redis config as to how it's persisted. More info [here](https://github.com/github/hubot/blob/master/docs/scripting.md#persistence).
