### ISSUE TITLE
Thoughts on extending this to other recurring daily events - add label/description?

### ISSUE THREAD

**Issue by victorhooi** [hubot-scripts/hubot-standup-alarm#3]
We're looking at using this for both daily morning standups, as well as the evening handovers.

Is it possible to extend this to make it more versatile to cover other recurring daily events.

I was thinking - maybe something as simple as having a "label" or "description" for each event, and then at the designated time, simply printing "<label> is on now" etc.

Thoughts?

**Comment by shaundon** [comment]
Haven't had a chance to do this lately - does anybody want to take it on?

**Comment by soupdiver** [comment]
Hey ya,
I'm currently looking for something more generic as you may suggested. Before I dig deeper into this repo I want to make sure that my changed would be the same stuff you intend to do :)

I'm looking for a script where I can add generic daily remembers like "production deploy", "update packages", "buy a new office cat" etc.

That stuff should be configurable on which weeks days and on which time the alarm should occur.

Is that the direction you want to go?

**Comment by shaundon** [comment]
Hey @soupdiver, that's exactly it! I guess it would work better as a fork, so that this repo is still around for people who just want the standup alarm, and then the more generic one for any event. I know I'd definitely make use of it!

**Comment by soupdiver** [comment]
Sweet!
I will look into this :)

**Comment by soupdiver** [comment]
@shaundon I think that would solve my use case: https://github.com/miyagawa/hubot-cron

**Comment by shaundon** [comment]
@soupdiver that looks pretty good, I might make use of it myself. Thanks! I'll close this issue now as hubot-cron looks like it'll do the job.
