### ISSUE TITLE
push latest version to NPM? 

### ISSUE THREAD

**Issue by jjmartin** [hubot-scripts/hubot-standup-alarm#32]
i'd like to get the latest version into our hubot so it supports the location/link  but the NPM doesn't have the latest code here - could you push it?

**Comment by contolini** [comment]
@shaundon This would be much appreciated. 🙇

**Comment by jjmartin** [comment]
i ended up just pushing the current code to our artifactory =P

**Comment by shaundon** [comment]
Hi all, really sorry for the delay - `0.1.0` is now on NPM.

**Comment by mattwwarren** [comment]
Could we get a 0.2.0 please? The day of the week fixes would be great.
