### ISSUE TITLE
Doesn't understand IRC rooms

### ISSUE THREAD

**Issue by docwhat** [hubot-scripts/hubot-standup-alarm#4]
When using it with the IRC adapter, it doesn't seem to understand IRC rooms (aka channels).

IRC channels are of the form `#foobar`.

Example output:

```
[11:23:53] @docwhat:	 hubot list standups in every room
[11:23:53] hubot:	 Here's the standups for every room:
[11:23:53] hubot:	 Room: undefined, Time: 10:00
[11:23:53] hubot:	 Room: undefined, Time: 11:45
```

I haven't hit 11:45am yet, so we'll see if it triggers or not.

**Comment by lornajane** [comment]
I have a pull request open for a similar room name problem, in case that helps https://github.com/hubot-scripts/hubot-standup-alarm/pulls/6

**Comment by docwhat** [comment]
That looks correct. Cool!

**Comment by shaundon** [comment]
Closing this, as it was fixed in https://github.com/hubot-scripts/hubot-standup-alarm/commit/d3608051d11a8df1cf8d051805f152f90e5868c4.
