### ISSUE TITLE
When using HipChat adapter, @here should be used to notify the room

### ISSUE THREAD

**Issue by MattTheRat** [hubot-scripts/hubot-standup-alarm#8]
People tend to ignore a message without something that draws their direct attention. In HipChat, this is easily accomplished by using @here.

I plan to make a pull request soon for this, possibly generalizing to an env var. Depends on complexity.

**Comment by shaundon** [comment]
Implemented in https://github.com/hubot-scripts/hubot-standup-alarm/commit/ba6b789e30dcd1a775824331ad2f1adce00ae606.
